name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"

      - run: poetry install

      - name: Lint tests with ruff
        run: |
          poetry run ruff check --no-fix .
      - name: Lint tests with mypy
        run: |
          poetry run mypy --install-types --non-interactive --ignore-missing-imports .
      - name: Test with pytest
        run: |
          poetry run pytest --cov=example tests
